project_name: five-hunerd
builds:
  - env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
archives:
  - format: zip
    wrap_in_directory: true
    files:
      - README.md
      - assets/*
    replacements:
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
